/*
* generated by Xtext
*/
package com.intel.llvm.ireditor;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LLVM_IRUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.intel.llvm.ireditor.ui.internal.LLVM_IRActivator.getInstance().getInjector("com.intel.llvm.ireditor.LLVM_IR");
	}
	
}
