/*
 * generated by Xtext
 */
package com.intel.llvm.ireditor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.intel.llvm.ireditor.ui.internal.LLVM_IRActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LLVM_IRExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LLVM_IRActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LLVM_IRActivator.getInstance().getInjector(LLVM_IRActivator.COM_INTEL_LLVM_IREDITOR_LLVM_IR);
	}
	
}
