/*
* generated by Xtext
*/
package com.intel.llvm.ireditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LLVM_IRAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/intel/llvm/ireditor/parser/antlr/internal/InternalLLVM_IR.tokens");
	}
}
